version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: gravy-postgres
    environment:
      POSTGRES_USER: gravy
      POSTGRES_PASSWORD: gravy
      POSTGRES_DB: gravy
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: >
      postgres
      -c max_connections=200

  redis:
    image: redis:7
    container_name: gravy-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
